import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Authcontext from '@/context/auth-context'
import { Toaster } from 'react-hot-toast'
import ConfettiProvider from '@/provider/confetti-provider'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <Toaster/>
      <ConfettiProvider/>
        <Authcontext>
        {children}
        </Authcontext>
        </body>
    </html>
  )
}
